__Exploratory Data Analysis (EDA)__

- Inspect distributions, missing values, outliers.
- Plot time series of IV, skew, curvature.
- Compare SPY vs QQQ.
- Correlation checks.
- Document findings.

In [ ]:
# import parquet_extractor  
# import importlib

# importlib.reload(parquet_extractor)

In [2]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller
from parquet_extractor import load_ticker_year_data, get_ticker_metadata

__Load the filtered parquet__

In [3]:
metadata = get_ticker_metadata('SPY', Path("."))
metadata

{'ticker': 'SPY',
 'processing_config': {'date_range': {'from_date': '2023-01-01',
   'to_date': '2023-01-31'},
  'volume_percentile': 0.95,
  'batch_size': 75000},
 'data_statistics': {'volume_threshold': 6075.0,
  'total_records_raw': 476003,
  'total_records_written': 476003,
  'filter_retention_rate': 1.0,
  'years_available': [2023]},
 'files_created': ['options_data_partitioned/spy/spy_2023.parquet'],
 'processing_timestamp': '2025-09-22T00:52:57.153881',
 'schema': {'date': 'Date',
  'secid': 'Float64',
  'symbol': 'String',
  'cp_flag': 'String',
  'exdate': 'Date',
  'strike_price': 'Float64',
  'best_bid': 'Float64',
  'best_offer': 'Float64',
  'volume': 'Float64',
  'open_interest': 'Float64',
  'impl_volatility': 'Float64',
  'delta': 'Float64',
  'vega': 'Float64',
  'theta': 'Float64',
  'forward_price': 'Float64',
  'expiry_indicator': 'String',
  'prc': 'Float64',
  'vol': 'Float64',
  'year': 'Int32',
  'month': 'Int8',
  'day': 'Int8',
  'iv_30d': 'Float64',
  'price_diff_1d': 'Float64',
  'price_diff_2d': 'Float64',
  'price_diff_3d': 'Float64',
  'price_diff_5d': 'Float64',
  'price_diff_8d': 'Float64',
  'price_diff_13d': 'Float64',
  'price_diff_21d': 'Float64',
  'price_diff_34d': 'Float64',
  'price_diff_55d': 'Float64',
  'price_diff_89d': 'Float64',
  'price_diff_144d': 'Float64',
  'price_diff_233d': 'Float64'}}

In [4]:
import polars as pl  # if you're using Polars
from pathlib import Path

def load_merged_ticker_data(tickers, start_year, end_year, data_dir=Path(".")):
    """Load and merge data for multiple tickers across a range of years."""
    all_data = []

    if isinstance(tickers, str):
        tickers = [tickers]

    for ticker in tickers:
        for year in range(start_year, end_year + 1):
            try:
                df = load_ticker_year_data(ticker, year, data_dir)
                df = df.with_columns([
                    pl.lit(ticker).alias("ticker"),
                ])
                all_data.append(df)
            except FileNotFoundError:
                print(f"Data not found for {ticker} in {year}, skipping.")
            except Exception as e:
                print(f"Error loading {ticker} in {year}: {e}")

    if all_data:
        return pl.concat(all_data)
    else:
        return pl.DataFrame()

In [5]:
spy_df = load_merged_ticker_data('SPY', 2016, 2023, Path(".")).to_pandas()
spy_df.sample(7)

,date,secid,symbol,cp_flag,exdate,strike_price,best_bid,best_offer,volume,open_interest,...,price_diff_5d,price_diff_8d,price_diff_13d,price_diff_21d,price_diff_34d,price_diff_55d,price_diff_89d,price_diff_144d,price_diff_233d,ticker
4600445,2019-06-27,109820.0,SPY 191220P247000,P,2019-12-20,247000.0,2.72,2.74,25.0,1815.0,...,0.00,1.03000,1.03000,-2.14001,-4.35999,1.92001,10.97000,4.84000,14.17001,SPY
8761492,2020-02-13,109820.0,SPY 200331C342000,C,2020-03-31,342000.0,2.84,2.87,405.0,23837.0,...,0.00,0.00000,0.00000,-0.36001,1.79999,2.38001,4.20001,9.38001,9.10999,SPY
3112765,2018-03-29,109820.0,SPY 180420C250000,C,2018-04-20,250000.0,15.03,15.28,101.0,3600.0,...,0.00,3.32000,2.54998,-1.96000,-0.52002,-7.80002,-11.85001,-9.73001,-9.96000,SPY
5322027,2019-05-28,109820.0,SPY 190614P286000,P,2019-06-14,286000.0,6.53,6.58,831.0,1910.0,...,0.00,0.00000,-2.63001,-2.63001,-1.99002,-6.36002,-5.69001,-0.71000,-13.88001,SPY
14498391,2022-07-27,109820.0,SPY 220916P422000,P,2022-09-16,422000.0,24.39,24.78,9.0,5385.0,...,10.15,10.15000,10.15000,5.47000,5.95001,6.27002,15.91001,16.81000,20.39002,SPY
12231106,2021-10-28,109820.0,SPY 211231P461000,P,2021-12-31,461000.0,12.64,12.70,55.0,51.0,...,0.00,0.00000,4.38001,4.38001,2.36002,5.20001,7.68000,20.46002,24.69001,SPY
14658531,2022-09-29,109820.0,SPY 230317C430000,C,2023-03-17,430000.0,3.54,4.30,163.0,5623.0,...,0.00,-7.73999,-7.73999,-7.73999,-0.58999,-5.16000,-14.60000,-27.32999,-27.97000,SPY

In [6]:
qqq_df = load_merged_ticker_data('QQQ', 2016, 2023, Path(".")).to_pandas()
qqq_df.sample(7)

,date,secid,symbol,cp_flag,exdate,strike_price,best_bid,best_offer,volume,open_interest,...,price_diff_5d,price_diff_8d,price_diff_13d,price_diff_21d,price_diff_34d,price_diff_55d,price_diff_89d,price_diff_144d,price_diff_233d,ticker
499641,2017-11-21,107899.0,QQQ 171229C148000,C,2017-12-29,148000.0,7.99,8.11,1.0,960.0,...,1.67000,1.67000,1.55000,0.96001,2.91000,1.82001,1.71001,3.92000,6.46001,QQQ
1047573,2019-10-04,107899.0,QQQ 191018C145000,C,2019-10-18,145000.0,43.68,44.42,2.0,7.0,...,0.00000,2.73999,4.76000,1.78000,-1.99000,-4.42000,0.89000,0.38001,-4.72000,QQQ
4511565,2023-02-09,107899.0,QQQ 230630C290000,C,2023-06-30,290000.0,28.27,28.51,1.0,5179.0,...,-2.69001,-2.69001,-2.69001,-8.20001,-1.91001,0.75998,5.41998,26.53000,35.94000,QQQ
381148,2017-07-13,107899.0,QQQ 171215P132000,P,2017-12-15,132000.0,2.69,2.77,56.0,2196.0,...,0.00000,0.00000,0.30999,1.95999,4.72000,3.41999,0.54998,-2.56002,2.61000,QQQ
537473,2017-12-21,107899.0,QQQ 171222C157000,C,2017-12-22,157000.0,0.65,0.69,1892.0,10910.0,...,-1.09000,-1.09000,-1.09000,1.67000,1.86000,2.85000,4.74000,1.36000,3.68000,QQQ
4320921,2022-03-21,107899.0,QQQ 230120C500000,C,2023-01-20,500000.0,0.65,0.85,26.0,4886.0,...,0.00000,-1.41000,-1.41000,5.63999,21.93000,15.09000,2.85999,8.56998,8.97998,QQQ
3663878,2022-08-19,107899.0,QQQ 240119C290000,C,2024-01-19,290000.0,66.47,69.10,1.0,536.0,...,-6.42001,-6.42001,-5.63000,-10.20001,-7.53002,5.78000,8.53000,20.87000,33.81998,QQQ

__Inspect distributions, missing values, outliers__

In [7]:
spy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17375323 entries, 0 to 17375322
Data columns (total 37 columns):
 #   Column             Dtype
---  ------             -----
 0   date               datetime64[ns]
 1   secid              float64
 2   symbol             object
 3   cp_flag            object
 4   exdate             datetime64[ns]
 5   strike_price       float64
 6   best_bid           float64
 7   best_offer         float64
 8   volume             float64
 9   open_interest      float64
 10  impl_volatility    float64
 11  delta              float64
 12  vega               float64
 13  theta              float64
 14  forward_price      float64
 15  expiry_indicator   object
 16  prc                float64
 17  vol                float64
 18  iv_30d             float64
 19  year               int32
 20  vol_delta_product  float64
 21  moneyness          float64
 22  volume_ma5         float64
 23  iv_rolling_std     float64
 24  price_diff_1d      float64
 25  price_diff_2d      float64
 26  price_diff_3d      float64
 27  price_diff_5d      float64
 28  price_diff_8d      float64
 29  price_diff_13d     float64
 30  price_diff_21d     float64
 31  price_diff_34d     float64
 32  price_diff_55d     float64
 33  price_diff_89d     float64
 34  price_diff_144d    float64
 35  price_diff_233d    float64
 36  ticker             object
dtypes: datetime64[ns](2), float64(30), int32(1), object(4)
memory usage: 4.7+ GB

In [8]:
spy_df.isna().sum()

date                        0
secid                       0
symbol                      0
cp_flag                     0
exdate                      0
strike_price                0
best_bid                    0
best_offer                  0
volume                      0
open_interest               0
impl_volatility             0
delta                       0
vega                        0
theta                       0
forward_price        17375323
expiry_indicator     12799393
prc                         0
vol                         0
iv_30d                      0
year                        0
vol_delta_product           0
moneyness                   0
volume_ma5                  0
iv_rolling_std              0
price_diff_1d               0
price_diff_2d               0
price_diff_3d               0
price_diff_5d               0
price_diff_8d               0
price_diff_13d              0
price_diff_21d              0
price_diff_34d              0
price_diff_55d              0
price_diff_89d              0
price_diff_144d             0
price_diff_233d             0
ticker                      0
dtype: int64

In [9]:
qqq_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5045603 entries, 0 to 5045602
Data columns (total 37 columns):
 #   Column             Dtype
---  ------             -----
 0   date               datetime64[ns]
 1   secid              float64
 2   symbol             object
 3   cp_flag            object
 4   exdate             datetime64[ns]
 5   strike_price       float64
 6   best_bid           float64
 7   best_offer         float64
 8   volume             float64
 9   open_interest      float64
 10  impl_volatility    float64
 11  delta              float64
 12  vega               float64
 13  theta              float64
 14  forward_price      float64
 15  expiry_indicator   object
 16  prc                float64
 17  vol                float64
 18  iv_30d             float64
 19  year               int32
 20  vol_delta_product  float64
 21  moneyness          float64
 22  volume_ma5         float64
 23  iv_rolling_std     float64
 24  price_diff_1d      float64
 25  price_diff_2d      float64
 26  price_diff_3d      float64
 27  price_diff_5d      float64
 28  price_diff_8d      float64
 29  price_diff_13d     float64
 30  price_diff_21d     float64
 31  price_diff_34d     float64
 32  price_diff_55d     float64
 33  price_diff_89d     float64
 34  price_diff_144d    float64
 35  price_diff_233d    float64
 36  ticker             object
dtypes: datetime64[ns](2), float64(30), int32(1), object(4)
memory usage: 1.4+ GB

In [10]:
qqq_df.isna().sum()

date                       0
secid                      0
symbol                     0
cp_flag                    0
exdate                     0
strike_price               0
best_bid                   0
best_offer                 0
volume                     0
open_interest              0
impl_volatility            0
delta                      0
vega                       0
theta                      0
forward_price        5045603
expiry_indicator     3986113
prc                        0
vol                        0
iv_30d                     0
year                       0
vol_delta_product          0
moneyness                  0
volume_ma5                 0
iv_rolling_std             0
price_diff_1d              0
price_diff_2d              0
price_diff_3d              0
price_diff_5d              0
price_diff_8d              0
price_diff_13d             0
price_diff_21d             0
price_diff_34d             0
price_diff_55d             0
price_diff_89d             0
price_diff_144d            0
price_diff_233d            0
ticker                     0
dtype: int64

In [ ]:
# Unique symbols
print(df['ticker'].unique())

# Or with counts
print(df['ticker'].value_counts())

In [ ]:
fig, axes = plt.subplots(2,1, figsize=(12,10))

# Distribution of IV
sns.histplot(data=df, x='impl_volatility', bins=50, kde=True, ax = axes[0])
axes[0].set_title("Distribution of Implied Volatility")

# Boxplot by symbol
sns.boxplot(x='ticker', y='impl_volatility', data=df, ax = axes[1])
axes[1].set_title("IV Distribution by Ticker")

plt.tight_layout()
plt.show()

Implied volatility is concentrated between roughly 15% and 30%, with very few outliers above 30%. This suggests the dataset is clean after filtering. SPY and QQQ show broadly similar IV distributions, with QQQ’s median only slightly higher, reflecting modest sector risk differences. Outliers above 0.3 may represent short‑term stress events or occasional bad quotes, but they are rare and do not dominate the distribution.

__Aggregate daily features (ATM IV, skew, curvature)__

In [ ]:
features = []

# Group by date and symbol (ticker)
for (date, ticker), group in df.groupby(['date','ticker']):
    group = group.copy()
    
    # --- ATM IV by delta ---
    atm_row = group.iloc[(group['delta'].abs() - 0.5).abs().argsort()[:1]]
    atm_iv = atm_row['impl_volatility'].values[0]

    # --- 25-delta put and call ---
    put25 = group.loc[group['cp_flag'] == 'P']
    call25 = group.loc[group['cp_flag'] == 'C']

    if not put25.empty and not call25.empty:
        put25_idx = (put25['delta'] + 0.25).abs().idxmin()
        call25_idx = (call25['delta'] - 0.25).abs().idxmin()

        iv_put25 = group.loc[put25_idx, 'impl_volatility']
        iv_call25 = group.loc[call25_idx, 'impl_volatility']

        skew = iv_put25 - iv_call25
        curvature = (iv_put25 + iv_call25) / 2 - atm_iv
    else:
        skew = curvature = np.nan

    features.append({
        'date': date,
        'ticker': ticker,
        'ATM_IV': atm_iv,
        'Skew': skew,
        'Curvature': curvature
    })

features_df = pd.DataFrame(features)
features_df.head()

Pull in the TBills Secondary Market 3-month (dtb3) and Treasury Constant Maturity 2-year (dgs2) from WRDS FRB and join by date

In [ ]:
db = wrds.Connection(wrds_username='ayansola')
# setup pg_pass needed for access to the wrds dataset (first time only)
# db.create_pgpass_file()

In [ ]:
params = {
    "from_date": "2022-01-01",
    "to_date": "2023-12-31"
}

t_bill = db.raw_sql(
    """
    SELECT date, dtb3 as tbills_3m, dgs2 as treasury_2y
    FROM frb.rates_daily
    WHERE date BETWEEN %(from_date)s AND %(to_date)s
    """,
    params=params,
)

In [ ]:
t_bill.dtypes

In [ ]:
t_bill['date'] = pd.to_datetime(t_bill['date'])

In [ ]:
t_bill.info()

In [ ]:
t_bill.head()

In [ ]:
features_df = features_df.merge(t_bill[['date','tbills_3m', 'treasury_2y']], on='date', how='left')

In [ ]:
features_df.head()

__Plot time series of IV, skew, curvature & compare SPY vs QQQ__

In [ ]:
fig, axes = plt.subplots(5,1, figsize=(12,16))

sns.lineplot(data=features_df, x='date', y='ATM_IV', hue='ticker', ax = axes[0])
axes[0].set_title("ATM IV Over Time")

sns.lineplot(data=features_df, x='date', y='Skew', hue='ticker', ax = axes[1])
axes[1].set_title("Skew Over Time")

sns.lineplot(data=features_df, x='date', y='Curvature', hue='ticker', ax = axes[2])
axes[2].set_title("Curvature Over Time")

sns.lineplot(data=features_df, x='date', y='tbills_3m', ax = axes[3])
axes[3].set_title("3 month TBills Secondary Market Over Time")

sns.lineplot(data=features_df, x='date', y='treasury_2y', ax = axes[4])
axes[4].set_title("Treasury Constant Maturity 2-year Over Time")


# sns.lineplot(data=features_df, x='date', y='dtb1yr', ax = axes[3])
# axes[6].set_title("1 year TBills Secondary Market Over Time")

plt.tight_layout()
plt.show()

- Both symbols experience occasional, brief volatility spikes, with QQQ’s being more pronounced.

- QQQ’s skew is more volatile and often higher, pointing to increased demand for put options

- Curvature is persistently positive for both

- Implied volatility doesn’t track with short‑term rates like the 3‑month bill, but it does respond more visibly to shifts in the 2‑year yield as seen above

In [ ]:
# drop dtb3 since IV doesn't track with it
features_df = features_df.drop(columns=['tbills_3m'])

__Correlation checks__

In [ ]:
metrics = ['ATM_IV', 'Skew', 'Curvature']

for metric in metrics:
    pivot = features_df.pivot(index='date', columns='ticker', values=metric)
    corr = pivot.corr()
    sns.heatmap(corr, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
    plt.title(f"Correlation of {metric} between SPY and QQQ")
    plt.show()

Volatility levels between SPY and QQQ are highly synchronized, skew is moderately aligned but allows for divergence, and curvature behaves almost independently.

In [ ]:
series = features_df[features_df['ticker']=='SPY']['ATM_IV']
result = adfuller(series.dropna())
print("ADF Statistic:", result[0])
print("p-value:", result[1])

### EDA Summary
- **Data quality:** No major missing values.
- **Distributions:** SPY && QQQ IV show broadly similar distributions with SPY IV centered lower than QQQ
- **Time series:** Both symbols show volatility spikes around market stress dates.
- **Correlations:** ATM IV highly correlated (SPY vs QQQ ~0.8).

__Save Aggregate daily features to Parquet: partition by symbol/year for downstream use.__

In [ ]:
features_df['year'] = pd.to_datetime(features_df['date']).dt.year

# Write to Parquet with partitioning
features_df.to_parquet(
    "features_parquet/",
    engine="fastparquet",        # or "pyarrow"
    partition_cols=["ticker", "year"],
    index=False
)